# This is an example gorelease.yaml file with some sane defaults.
# Make sure to check the documentation at http://gorelease.com
project_name: ory

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

universal_binaries:
- id: ory
  replace: true

builds:
  -
    id: ory-sqlite-darwin
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
      - arm64
    goos:
      - darwin

  -
    id: ory-sqlite-linux
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
      - arm64
    goos:
      - linux

  -
    id: ory-sqlite-linux-libmusl
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
      - arm64
    goos:
      - linux

  -
    id: ory-sqlite-windows
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
      - "-extldflags '-static'"
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

  -
    id: ory
    flags:
      - -tags
      - nodev
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - linux
      - windows
      - darwin

archives:
  - builds:
    - ory-sqlite-windows
    id: ory-windows
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: ory-macos
    builds:
      - kratos-sqlite-darwin-arm
      - kratos-sqlite-darwin
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - builds:
    - ory-sqlite-linux
    id: ory-linux
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - builds:
      - ory-sqlite-linux-libmusl
    id: ory-linux-libmusl
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-libmusl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  -
    name: cli
    description: Interface with Ory using this CLI!
    license: "Apache-2.0"
    tap:
      owner: ory
      name: homebrew-tap
    goarm: 6
    test: |
      system "#{bin}/ory version"
    ids:
      - ory-sqlite-darwin
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: 3372410+aeneasr@users.noreply.github.com

scoop:
  bucket:
    owner: ory
    name: scoop-ory
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: aeneas@ory.sh

release:
  prerelease: auto

dockers:
  - image_templates:
      - "oryd/ory:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    ids:
      - ory
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "oryd/ory:{{ .Version }}-arm64/v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    ids:
      - ory
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  # You can have multiple Docker manifests.
  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: tag

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/ory:{{ .Tag }}"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/ory:{{ .Tag }}-amd64"
      - "oryd/ory:{{ .Tag }}-arm64/v8"

  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: latest

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/ory:latest"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/ory:latest-amd64"
      - "oryd/ory:latest-arm64/v8"
