# This is an example gorelease.yaml file with some sane defaults.
# Make sure to check the documentation at http://gorelease.com
project_name: ory

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

universal_binaries:
- id: default
  replace: true

builds:
  -
    id: macos-cgo
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
      - arm64
    goos:
      - darwin

  -
    id: linux-cgo-amd64
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux

  -
    id: linux-cgo-arm64
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goarch:
      - arm64
    goos:
      - linux

  -
    id: linux-cgo-arm
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
    goarch:
      - arm
    goarm:
      - 5
      - 6
      - 7
    goos:
      - linux

  -
    id: alpine-cgo
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux

  -
    id: windows-cgo
    flags:
      - -tags
      - sqlite
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

  -
    id: default
    flags:
      - -tags
      - nodev
    ldflags:
      - "-s -w -X github.com/ory/cli/buildinfo.Version={{.Tag}} -X github.com/ory/cli/buildinfo.GitHash={{.FullCommit}} -X github.com/ory/cli/buildinfo.Time={{.Date}}"
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: windows-cgo
    builds:
    - windows-cgo
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-sqlite_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: macos-cgo
    builds:
      - macos-cgo
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-sqlite_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: linux-cgo
    builds:
    - linux-cgo-arm64
    - linux-cgo-amd64
    - linux-cgo-arm
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-sqlite_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: alpine-cgo
    builds:
      - alpine-cgo
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-sqlite-libmusl_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: default
    builds:
      - default
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  -
    name: cli
    description: Interface with Ory using this CLI!
    license: "Apache-2.0"
    tap:
      owner: ory
      name: homebrew-tap
    goarm: 6
    test: |
      system "#{bin}/{{ .ProjectName }} version"
    ids:
      - macos-cgo
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: 3372410+aeneasr@users.noreply.github.com

scoop:
  bucket:
    owner: ory
    name: scoop-{{ .ProjectName }}
  homepage: https://www.ory.sh
  commit_author:
    name: aeneasr
    email: 3372410+aeneasr@users.noreply.github.com

release:
  prerelease: auto

dockers:
  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    goarch: amd64
    ids:
      - linux-cgo-amd64
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    ids:
      - linux-cgo-arm64
    build_flag_templates:
      - "--platform=linux/arm64"

  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-armv7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    ids:
      - linux-cgo-arm
    build_flag_templates:
      - "--platform=linux/arm/v7"

  - image_templates:
      - "oryd/{{ .ProjectName }}:v{{ .Version }}-armv6"
    use: buildx
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    ids:
      - linux-cgo-arm
    build_flag_templates:
      - "--platform=linux/arm/v6"

docker_manifests:
  # You can have multiple Docker manifests.
  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: tag

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/{{ .ProjectName }}:{{ .Tag }}"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv6"

  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: major

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/{{ .ProjectName }}:vv{{ .Major }}"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv6"

  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: minor

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv6"

  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: patch

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv6"

  -
    # ID of the manifest, needed if you want to filter by it later on (e.g. on custom publishers).
    id: latest

    # Name template for the manifest.
    # Defaults to empty.
    name_template: "oryd/{{ .ProjectName }}:latest"

    # Image name templates to be added to this manifest.
    # Defaults to empty.
    image_templates:
      - "oryd/{{ .ProjectName }}:latest-amd64"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "oryd/{{ .ProjectName }}:{{ .Tag }}-armv6"
