# This is an example gorelease.yaml file with some sane defaults.
# Make sure to check the documentation at http://gorelease.com
project_name: ory

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - git checkout -- go.sum

builds:
  -
    id: ory-sqlite-darwin
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
      # - "-extldflags '-static'"
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin

  -
    id: ory-sqlite-linux
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
  -
    id: ory-sqlite-linux-libmusl
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux
  -
    id: ory-sqlite-windows
    flags:
      - -tags
      - sqlite
      # Remove once https://github.com/golang/go/issues/40795 is closed
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/ory/cli/x.BuildVersion={{.Tag}} -X github.com/ory/cli/x.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/x.BuildTime={{.Date}}
      - "-extldflags '-static'"
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

archives:
  - builds:
    - ory-sqlite-windows
    id: ory-windows
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

  - builds:
    - ory-sqlite-darwin
    id: ory-macos
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

  - builds:
    - ory-sqlite-linux
    id: ory-linux
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

  - builds:
      - ory-sqlite-linux-libmusl
    id: ory-linux-libmusl
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}-libmusl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  -
    tap:
      owner: ory
      name: homebrew-ory
    goarm: 6
    ids:
      - ory-macos
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: aeneas@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-ory
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: aeneas@ory.sh

release:
  prerelease: auto

dockers:
  - dockerfile: Dockerfile
    ids:
      - ory-sqlite-linux-libmusl
    image_templates:
      - "oryd/ory:{{ .Tag }}"
      - "oryd/ory:latest"
