includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/a796a4dd9aa8c6e93190004c748c46a9c497586a/build.tmpl.yml

variables:
  brew_name: cli

  brew_description: "Use Ory from the your terminal!"

  buildinfo_hash: "github.com/ory/cli/buildinfo.GitHash"
  buildinfo_tag: "github.com/ory/cli/buildinfo.Version"
  buildinfo_date: "github.com/ory/cli/buildinfo.Time"

project_name: ory
