FROM alpine:3.22

RUN apk add -U --no-cache ca-certificates libssl3 libcrypto3 bash

RUN addgroup -S ory; \
    adduser -S ory -G ory -D  -h /home/ory -s /bin/nologin; \
    chown -R ory:ory /home/ory

COPY ory /usr/bin/ory

USER ory

ENTRYPOINT ["ory"]
